// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type Channel struct {
	ID          string
	ChannelName string
	ChannelUrl  string
	IsSubbed    bool
}

type Video struct {
	ID         string
	VideoType  string
	VideoTitle string
	ChannelID  string
}

type WatchHistory struct {
	WatchHistoryID int64
	VideoID        string
	WatchedAt      string
}
