// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: subscribers.sql

package db

import (
	"context"
)

const addChannel = `-- name: AddChannel :one
INSERT INTO channels (
    id,
    channel_name,
    channel_url,
    is_subbed

    ) VALUES (
        ?, ?, ?, ?
) RETURNING id, channel_name, channel_url, is_subbed
`

type AddChannelParams struct {
	ID          string
	ChannelName string
	ChannelUrl  string
	IsSubbed    bool
}

func (q *Queries) AddChannel(ctx context.Context, arg AddChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, addChannel,
		arg.ID,
		arg.ChannelName,
		arg.ChannelUrl,
		arg.IsSubbed,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ChannelName,
		&i.ChannelUrl,
		&i.IsSubbed,
	)
	return i, err
}
