// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: videos.sql

package db

import (
	"context"
)

const addVideo = `-- name: AddVideo :one
INSERT INTO videos (
    id,
    video_type,
    video_title,
    channel_id
)VALUES (
        ?, ?, ?, ?
) RETURNING id, video_type, video_title, channel_id
`

type AddVideoParams struct {
	ID         string
	VideoType  string
	VideoTitle string
	ChannelID  string
}

func (q *Queries) AddVideo(ctx context.Context, arg AddVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, addVideo,
		arg.ID,
		arg.VideoType,
		arg.VideoTitle,
		arg.ChannelID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoType,
		&i.VideoTitle,
		&i.ChannelID,
	)
	return i, err
}
