// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: watch_history.sql

package db

import (
	"context"
	"database/sql"
)

const addWatchHistory = `-- name: AddWatchHistory :one
INSERT INTO watch_history (
    
    video_id,
    watched_at,
    channel_id
)VALUES (
         ?, ?, ?
) RETURNING id, video_id, watched_at, channel_id
`

type AddWatchHistoryParams struct {
	VideoID   sql.NullString
	WatchedAt string
	ChannelID sql.NullString
}

func (q *Queries) AddWatchHistory(ctx context.Context, arg AddWatchHistoryParams) (WatchHistory, error) {
	row := q.db.QueryRowContext(ctx, addWatchHistory, arg.VideoID, arg.WatchedAt, arg.ChannelID)
	var i WatchHistory
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.WatchedAt,
		&i.ChannelID,
	)
	return i, err
}
